version: '3'
services:
  flask-app:
    build: ./flask-app
    volumes:
      - ./flask-app:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
    - 27017:27017
    volumes:
      - ./data:/data/db
  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    depends_on:
    - mongo
  db:
    environment:
      - POSTGRES_USER=odoodev
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    image: postgres:10
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata
  smtp:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
  db_web:
    image: fenglc/pgadmin4:2.1
    environment:
      - DEFAULT_USER=odoodev
      - DEFAULT_PASSWORD=odoo
      - MAIL_SERVER=smtp
      - MAIL_PORT=1025
    links:
      - db
      - smtp
    ports:
      - "5050:5050"
  debug:
    image: kozea/wdb-server
    ports:
      - "1984:1984"
  odoo:
    build: ./odoo
    ports:
      - "8069:8069"
      - "9999:9999"
      - "8071:8071"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./:/mnt/extra-addons
    links:
      - db
      - db_web
      - smtp
      - debug
    environment:
      - PGHOST=db
      - USER=odoodev
      - PASSWORD=odoo
      - WDB_SOCKET_SERVER=debug
      - WDB_NO_BROWSER_AUTO_OPEN=True
    command: ["-d","odoodev","--init","microservice"]
volumes:
  dbdata:
  odoo-web-data: